embedding_size: 64
feat_embed_dim: 64


n_layers: 2
mm_image_weight: 0.5
aggr_mode: 'add'
knn_k: 10
k: 40
ii_layers: [1]
ui_layers: [2]
learning_rate: [0.0001]
reg_weight: [0.01]
fuse: None # None, 'pid', 'concat', 'pool', 'comm', 'prism'
hyper_parameters: ["ui_layers", "ii_layers", "reg_weight", "learning_rate"]
