# coding: utf-8
# 
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
from .jepa import PIDJEPA


class VLIF(GeneralRecommender):
    def __init__(self, config, dataset):
        super(VLIF, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        batch_size = config['train_batch_size']         # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.ii_layers = config['ii_layers']
        self.knn_k = config['knn_k']
        self.mm_image_weight = config['mm_image_weight']
        has_id = True

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = config['ui_layers']
        self.dataset = dataset
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.dim_latent = 64
        self.dim_feat = 128
        self.mm_adj = None
        self.synergy_weight = 0.1
        self.fuse = config['fuse']

        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        self.user_graph_dict = np.load(os.path.join(dataset_path, config['user_graph_dict_file']), allow_pickle=True).item()
        
        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

        if self.v_feat is not None:
            _, image_adj = self.get_knn_adj_mat(self.v_feat.detach())
            self.mm_adj = image_adj
        if self.t_feat is not None:
            _, text_adj = self.get_knn_adj_mat(self.t_feat.detach())
            self.mm_adj = text_adj
        if self.v_feat is not None and self.t_feat is not None:
            self.mm_adj = self.mm_image_weight * image_adj + (1.0 - self.mm_image_weight) * text_adj
            del text_adj
            del image_adj

        # packing interaction in training into edge_index
        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)
        edge_index = self.pack_edge_index(train_interactions)
        self.edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)

        # pdb.set_trace()
        numWeight = 2
        if self.fuse in ['pid', 'pool', 'concat']:
            numWeight = 4
            self.user_s = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                            np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                            gain=1).to(self.device))
            
            self.user_r = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                            np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                            gain=1).to(self.device))
        self.user_ut = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                                    np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                                    gain=1).to(self.device))
        self.user_uv = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                        np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                        gain=1).to(self.device))
        self.weight_u = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_user, numWeight, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_u.data = F.softmax(self.weight_u, dim=1)

        if self.v_feat is not None:
            self.v_gcn = GCN(self.aggr_mode, num_layer=self.num_layer, dim_latent=64, device=self.device) 
        if self.t_feat is not None:
            self.t_gcn = GCN(self.aggr_mode, num_layer=self.num_layer, dim_latent=64, device=self.device)
            self.s_gcn = GCN(self.aggr_mode, num_layer=self.num_layer, dim_latent=64, device=self.device)
            self.r_gcn = GCN(self.aggr_mode, num_layer=self.num_layer, dim_latent=64, device=self.device)

        self.user_graph = User_Graph_sample(num_user, 'add', self.dim_latent)
        if self.fuse == 'pid':
            self.fuseFn = PIDJEPA()
        elif self.fuse == 'concat':
            self.fuseFn = nn.Linear(self.v_feat.size(1) * 2, self.dim_latent)
        elif self.fuse == 'pool':
            self.fuseFn = nn.Linear(self.v_feat.size(1), self.dim_latent)

        self.rProj = nn.Linear(self.dim_latent, self.t_feat.size(1), bias=False)
    

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)
    
    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    
    def pre_epoch_processing(self):
        self.epoch_user_graph, self.user_weight_matrix = self.topk_sample(self.k)
        self.user_weight_matrix = self.user_weight_matrix.to(self.device)

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def item_item(self, rep):
        h = rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return rep + h

    def forward(self, interaction):
        user_nodes, pos_item_nodes, neg_item_nodes = interaction[0], interaction[1], interaction[2]
        pos_item_nodes += self.n_users
        neg_item_nodes += self.n_users

        if self.fuse in ['pid', 'pool', 'concat']:
            if self.fuse == 'pid':
                outputs = self.fuseFn(self.v_feat, self.t_feat)
                losses = self.fuseFn.compute_losses(outputs)
                self.jepaLoss = losses['loss']
                sFeat, rFeat = outputs['target_s'], outputs['rF']
            elif self.fuse == 'concat':
                sFeat = self.fuseFn(torch.cat((self.v_feat, self.t_feat), dim=1))
            elif self.fuse == 'pool':
                sFeat = self.fuseFn((self.v_feat + self.t_feat) / 2)
            self.s_rep = self.s_gcn(self.edge_index, sFeat, self.user_s)
            self.r_rep = self.r_gcn(self.edge_index, rFeat, self.user_r)
            prj = self.rProj(rFeat)
            prj = F.leaky_relu(prj)
        vfeat = self.image_trs(self.v_feat)
        tfeat = self.text_trs(self.t_feat)
        self.v_rep = self.v_gcn(self.edge_index, vfeat, self.user_uv)
        self.t_rep = self.t_gcn(self.edge_index, tfeat, self.user_ut)
    
        item_repV = self.v_rep[self.num_user:]
        item_repT = self.t_rep[self.num_user:]
        if self.fuse in ['pid', 'pool', 'concat']:
            item_repS = self.s_rep[self.num_user:]
            item_repR = self.r_rep[self.num_user:]
            item_rep = torch.cat((item_repT, item_repV, item_repS, item_repR), dim=1)
        else:
            item_rep = torch.cat((item_repT, item_repV), dim=1)
        item_rep = self.item_item(item_rep)


        user_repV = self.v_rep[:self.num_user]
        user_repV = user_repV.unsqueeze(2)
        user_repT = self.t_rep[:self.num_user]
        user_repT = user_repT.unsqueeze(2)
        if self.fuse in ['pid', 'pool', 'concat']:
            user_repS = self.s_rep[:self.num_user]
            user_repS = user_repS.unsqueeze(2)
            user_repR = self.r_rep[:self.num_user]
            user_repR = user_repR.unsqueeze(2)
            user_rep = torch.cat((user_repT, user_repV, user_repS, user_repR), dim=2)
            user_rep = self.weight_u.transpose(1,2)*user_rep
            user_rep = torch.cat((user_rep[:,:,0], user_rep[:,:,1], user_rep[:,:,2], user_rep[:,:,3]), dim=1)
        else:
            user_rep = torch.cat((user_repT, user_repV), dim=2)
            user_rep = self.weight_u.transpose(1,2)*user_rep
            user_rep = torch.cat((user_rep[:,:,0], user_rep[:,:,1]), dim=1)

        h_u = self.user_graph(user_rep, self.epoch_user_graph, self.user_weight_matrix)
        # comment/remove the coefficient 0.5 for cloth dataset
        user_rep = 0.5 * (user_rep + h_u)
        

        self.result_embed = torch.cat((user_rep, item_rep), dim=0)
        user_tensor = self.result_embed[user_nodes]
        pos_item_tensor = self.result_embed[pos_item_nodes]
        neg_item_tensor = self.result_embed[neg_item_nodes]
        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        return pos_scores, neg_scores

    def calculate_loss(self, interaction):
        user = interaction[0]
        pos_scores, neg_scores = self.forward(interaction)
        loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
        if self.fuse != 'pid':
            self.jepaLoss = 0.0
        
        reg_loss = self.reg_weight * (self.weight_u ** 2).mean()
        return loss_value + reg_loss + self.jepaLoss

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

    def topk_sample(self, k):
        user_graph_index = []
        count_num = 0
        user_weight_matrix = torch.zeros(len(self.user_graph_dict), k)
        tasike = []
        for i in range(k):
            tasike.append(0)
        for i in range(len(self.user_graph_dict)):
            if len(self.user_graph_dict[i][0]) < k:
                count_num += 1
                if len(self.user_graph_dict[i][0]) == 0:
                    # pdb.set_trace()
                    user_graph_index.append(tasike)
                    continue
                user_graph_sample = self.user_graph_dict[i][0][:k]
                user_graph_weight = self.user_graph_dict[i][1][:k]
                while len(user_graph_sample) < k:
                    rand_index = np.random.randint(0, len(user_graph_sample))
                    user_graph_sample.append(user_graph_sample[rand_index])
                    user_graph_weight.append(user_graph_weight[rand_index])
                user_graph_index.append(user_graph_sample)


                if self.user_aggr_mode == 'softmax':
                    user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
                if self.user_aggr_mode == 'mean':
                    user_weight_matrix[i] = torch.ones(k) / k  # mean
                continue
            user_graph_sample = self.user_graph_dict[i][0][:k]
            user_graph_weight = self.user_graph_dict[i][1][:k]

            if self.user_aggr_mode == 'softmax':
                user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
            if self.user_aggr_mode == 'mean':
                user_weight_matrix[i] = torch.ones(k) / k  # mean
            user_graph_index.append(user_graph_sample)

        # pdb.set_trace()
        return user_graph_index, user_weight_matrix

class User_Graph_sample(torch.nn.Module):
    def __init__(self, num_user, aggr_mode,dim_latent):
        super(User_Graph_sample, self).__init__()
        self.num_user = num_user
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode

    def forward(self, features,user_graph,user_matrix):
        index = user_graph
        u_features = features[index]
        user_matrix = user_matrix.unsqueeze(1)
        # pdb.set_trace()
        u_pre = torch.matmul(user_matrix,u_features)
        u_pre = u_pre.squeeze()
        return u_pre


class GCN(torch.nn.Module):
    def __init__(self, aggr_mode, num_layer, dim_latent=None,device = None):
        super(GCN, self).__init__()
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.num_layer = num_layer
        self.device = device

        self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self,edge_index,features_item, feature_user):
        x = torch.cat((feature_user, features_item), dim=0).to(self.device)
        x = F.normalize(x).to(self.device)
        res = [x]
        for i in range(self.num_layer):
            x = self.conv_embed_1(x, edge_index)
            res.append(x)
        x_hat = sum(res)
        return x_hat


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index, size=None):
        # pdb.set_trace()
        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j, edge_index, size):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            return norm.view(-1, 1) * x_j
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)


